# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('registration', '0018_creditnote_creditnoteapplication_creditnoterefund'), ('registration', '0019_auto_20160410_0753')]

    dependencies = [
        ('registration', '0017_auto_20160408_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('paymentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.PaymentBase')),
            ],
            bases=('registration.paymentbase',),
        ),
        migrations.CreateModel(
            name='CreditNoteApplication',
            fields=[
                ('paymentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.PaymentBase')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.CreditNote')),
            ],
            bases=('registration.paymentbase',),
        ),
        migrations.CreateModel(
            name='CreditNoteRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(max_length=255)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.CreditNote')),
            ],
        ),
    ]
